apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-allication
  namespace: argocd
spec:
  project: default
  source:
    sourceRepo: 'https://github.com/madeshnandu90/helm-repo'
    targetRevision: HEAD
    path: /
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
  
