
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-allication
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/madeshnandu90/helm-repo-with-argocd'
    targetRevision: HEAD
    path: argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
  
