apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: back-end
spe:
  replicas: 1
  template:
    spe:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres-db"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
    volumes:
    - name: postgres-storage
      emptyDir: {}           
